---

- name: Automate Cisco ACI
  hosts: aci
  gather_facts: false
  pre_tasks:
    - name: Ensure ACI login data is provided via environment variables
      ansible.builtin.assert:
        that:
          - lookup('ansible.builtin.env', 'ACI_HOST') | length > 0
          - lookup('ansible.builtin.env', 'ACI_USERNAME') | length > 0
          - lookup('ansible.builtin.env', 'ACI_PASSWORD') | length > 0
          - lookup('ansible.builtin.env', 'ACI_VALIDATE_CERTS') | length > 0
        quiet: true
        fail_msg: "Login credentials not found! Provide environment variables, for example: 'export ACI_HOST=aci-api-endpoint'"
  roles:
    - aci-automation
