---
- name: Reset password of local user in Automation platform
  hosts: aap_api
  gather_facts: false
  module_defaults:
    group/ansible.controller.controller:
      controller_host: "{{ controller_hostname }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
  vars:
    reset_user: tgruetz
  tasks:
    - name: Ensure required variables are set
      ansible.builtin.assert:
        that:
          - reset_user is defined
          - reset_user | length > 0
        quiet: true
        fail_msg: "User {{ reset_user }} is not configured!"

    - name: Export all users
      ansible.controller.export:
        users: 'all'
      register: aap_config_export

    - name: Ensure that user is present
      ansible.builtin.assert:
        that:
          - reset_user in (aap_config_export.assets.users | map(attribute='username') | list)
        quiet: true
        fail_msg: "User {{ reset_user }} is not configured!"

    - name: Reset password for user {{ reset_user }}
      ansible.controller.user:
        username: "{{ reset_user }}"
        password: "Changeme!"
