---

- name: Install webserver
  yum:
    name: httpd
    state: present
  become: true

- name: Copy index.html template
  template:
    src: welcome.html
    dest: /var/www/html/index.html
    owner: apache
    group: apache
  become: true

- name: Start webserver
  service:
    name: httpd
    state: started
  become: true

- name: Output Info for Webserver access
  debug:
    msg: "Open your browser and input this address >> http://{{ ansible_host }}"
