---

controller_host: https://student1.rhff1d.example.opentlc.com/
controller_username: "{{ vault_controller_username | default('admin') }}"
controller_password: "{{ vault_controller_password | default('password') }}"
