---

- name: Create project
  awx.awx.project:
    name: 1hDD Demo
    description: Secure supply-chain demo for 1hDD
    organization: Default
    scm_type: git
    scm_url: https://github.com/TimGrt/automation-demo.git
    scm_clean: true
    scm_update_on_launch: true
    state: present

- name: Create inventory
  awx.awx.inventory:
    name: 1hDD Demo inventory
    description: Inventory for 1hDD Demo
    organization: Default

- name: Create host for inventory
  awx.awx.host:
    name: Fedora 37
    inventory: 1hDD Demo inventory

- name: Create Job template
  awx.awx.job_template:
    name: 1hDD - Deploy container
    description: Secure supply-chain demo for 1hDD
    organization: Default
    inventory: 1hDD Demo inventory
    project: 1hDD Demo
    playbook: 1hDD-Demo.yml
    credentials: Demo Credential
      