---
driver:
  name: podman
platforms:
  - name: rocky8
    image: timgrt/rockylinux8-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    command: "/usr/sbin/init"
    pre_build_image: true
    exposed_ports:
      - 80/tcp
    published_ports:
      - 8080:80/tcp
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_result_format: yaml
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      rocky8:
        ansible_user: ansible
scenario:
  create_sequence:
    - create
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - create
    - syntax
    - converge
    - idempotence
    - destroy
