---

- name: Create project
  awx.awx.project:
    name: 1hDD Demo
    description: Secure supply-chain demo for 1hDD
    organization: Default
    scm_type: git
    scm_url: https://github.com/TimGrt/automation-demo.git
    scm_clean: true
    scm_update_on_launch: true
    state: present

- name: Create credential for CCloud Container registry
  awx.awx.credential:
    name: CCloud Container Registry
    credential_type: Container Registry
    organization: Default
    inputs:
      host: registry.ccloud.ninja
      username: tgruetzmacher
      password: "{{ ccloud_cr_access_token }}"
    update_secrets: "{{ update_secrets | default(false) }}"

- name: Create Execution Environment
  awx.awx.execution_environment:
    name: 1hDD Demo EE
    image: registry.ccloud.ninja/tgruetzmacher/ansible-ee-demo
    pull: missing
    organization: Default
    credential: CCloud Container Registry

# Using already present Workshop Inventory and Machine Credential
- name: Create Job template
  awx.awx.job_template:
    name: 1hDD - Deploy container
    description: Secure supply-chain demo for 1hDD
    organization: Default
    inventory: Workshop Inventory
    project: 1hDD Demo
    playbook: 1hDD-Demo.yml
    become_enabled: true
    credentials: Workshop Credential
    execution_environment: 1hDD Demo EE
    limit: node2
