---

- name: Gather facts for all containers
  containers.podman.podman_container_info:
    name: welcome-{{ attendee_normalized }}
  changed_when: attendee_container_info.stderr_lines | length == 0
  register: attendee_container_info
  notify: Container_info

# - name: Container is already running, output info
#   ansible.builtin.debug:
#     msg: "Open your browser and input this address >> http://{{ ansible_host }}:{{ attendee_container_port }}"
#   when: attendee_container_info.stderr_lines | length == 0
#   vars:
#     attendee_container_port: "{{ attendee_container_info['containers'][0]['NetworkSettings']['Ports']['80/tcp'][0]['HostPort'] }}"

- name: No container running, creating new one...
  ansible.builtin.include_tasks: build-and-run-container.yml
  when: attendee_container_info.stderr_lines | length != 0
