---
name: Deploy to Github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: Deploy MkDocs project to Github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip3 install -r requirements.txt
      - run: mkdocs gh-deploy --force
